/*-------------------------------------------------------------

keymaps.c -- keyboard mappings

Copyright (C) 2008, 2009
Brian Johnson brijohn@gmail.com
dhewg

This software is provided 'as-is', without any express or implied
warranty.  In no event will the authors be held liable for any
damages arising from the use of this software.

Permission is granted to anyone to use this software for any
purpose, including commercial applications, and to alter it and
redistribute it freely, subject to the following restrictions:

1.	The origin of this software must not be misrepresented; you
must not claim that you wrote the original software. If you use
this software in a product, an acknowledgment in the product
documentation would be appreciated but is not required.

2.	Altered source versions must be plainly marked as such, and
must not be misrepresented as being the original software.

3.	This notice may not be removed or altered from any source
distribution.

-------------------------------------------------------------*/


#include "keymapper.h"
#include <wiikeyboard/keyboard_keysym.h>

BEGIN_KEYMAP(kbdmap_US, 123)
	MAP(4, a, A)
	MAP(5, b, B)
	MAP(6, c, C)
	MAP(7, d, D)
	MAP(8, e, E)
	MAP(9, f, F)
	MAP(10, g, G)
	MAP(11, h, H)
	MAP(12, i, I)
	MAP(13, j, J)
	MAP(14, k, K)
	MAP(15, l, L)
	MAP(16, m, M)
	MAP(17, n, N)
	MAP(18, o, O)
	MAP(19, p, P)
	MAP(20, q, Q)
	MAP(21, r, R)
	MAP(22, s, S)
	MAP(23, t, T)
	MAP(24, u, U)
	MAP(25, v, V)
	MAP(26, w, W)
	MAP(27, x, X)
	MAP(28, y, Y)
	MAP(29, z, Z)
	MAP(30, 1, exclam)
	MAP(31, 2, at)
	MAP(32, 3, numbersign)
	MAP(33, 4, dollar)
	MAP(34, 5, percent)
	MAP(35, 6, asciicircum)
	MAP(36, 7, ampersand)
	MAP(37, 8, asterisk)
	MAP(38, 9, parenleft)
	MAP(39, 0, parenright)
	MAP(45, minus, underscore)
	MAP(46, plus, equal)
	MAP(47, bracketleft, braceleft)
	MAP(48, bracketright, braceright)
	MAP(49, backslash, bar)
	MAP(51, semicolon, colon)
	MAP(52, apostrophe, quotedbl)
	MAP(53, grave, asciitilde)
	MAP(54, comma, less)
	MAP(55, period, greater)
	MAP(56, slash, question)
	MAP(40, return, null)
	MAP(41, escape, null)
	MAP(42, backspace, null)
	MAP(43, tab, null)
	MAP(44, space, null)
	MAP(57, Capslock, null)
	MAP(58, F1, null)
	MAP(59, F2, null)
	MAP(60, F3, null)
	MAP(61, F4, null)
	MAP(62, F5, null)
	MAP(63, F6, null)
	MAP(64, F7, null)
	MAP(65, F8, null)
	MAP(66, F9, null)
	MAP(67, F10, null)
	MAP(68, F11, null)
	MAP(69, F12, null)
	MAP(70, Print, null)
	MAP(71, Scrollock, null)
	MAP(72, pause, null)
	MAP(73, Insert, null)
	MAP(74, Home, null)
	MAP(75, Pageup, null)
	MAP(76, delete, null)
	MAP(77, End, null)
	MAP(78, Pagedown, null)
	MAP(79, Right, null)
	MAP(80, Left, null)
	MAP(81, Down, null)
	MAP(82, Up, null)
	MAP(83, Numlock, null)
	MAP(84, KP_slash, null)
	MAP(85, KP_asterisk, null)
	MAP(86, KP_minus, null)
	MAP(87, KP_plus, null)
	MAP(88, KP_enter, null)
	MAP(89, KP_1, null)
	MAP(90, KP_2, null)
	MAP(91, KP_3, null)
	MAP(92, KP_4, null)
	MAP(93, KP_5, null)
	MAP(94, KP_6, null)
	MAP(95, KP_7, null)
	MAP(96, KP_8, null)
	MAP(97, KP_9, null)
	MAP(98, KP_0, null)
	MAP(99, KP_period, null)
	MAP(101, Application, null)
	MAP(102, Power, null)
	MAP(103, KP_equal, null)
	MAP(104, F13, null)
	MAP(105, F14, null)
	MAP(106, F15, null)
	MAP(116, Execute, null)
	MAP(117, Help, null)
	MAP(118, Menu, null)
	MAP(119, Select, null)
	MAP(120, Stop, null)
	MAP(121, Again, null)
	MAP(122, Undo, null)
	MAP(123, Cut, null)
	MAP(124, Copy, null)
	MAP(125, Paste, null)
	MAP(126, Find, null)
	MAP(127, Mute, null)
	MAP(128, Volumeup, null)
	MAP(129, Volumedown, null)
	MAP(224, LeftCtrl, null)
	MAP(225, LeftShift, null)
	MAP(226, LeftAlt, null)
	MAP(227, LeftMeta, null)
	MAP(228, RightCtrl, null)
	MAP(229, RightShift, null)
	MAP(230, RightAlt, null)
	MAP(231, RightMeta, null)
END_KEYMAP

BEGIN_KEYMAP(kbdmap_DE, 124)
	MAP(4, a, A)
	MAP(5, b, B)
	MAP(6, c, C)
	MAP(7, d, D)
	MAP(8, e, E)
	MAP(9, f, F)
	MAP(10, g, G)
	MAP(11, h, H)
	MAP(12, i, I)
	MAP(13, j, J)
	MAP(14, k, K)
	MAP(15, l, L)
	EXT_MAP(16, m, M, mu, null)
	MAP(17, n, N)
	MAP(18, o, O)
	MAP(19, p, P)
	EXT_MAP(20, q, Q, at, null)
	MAP(21, r, R)
	MAP(22, s, S)
	MAP(23, t, T)
	MAP(24, u, U)
	MAP(25, v, V)
	MAP(26, w, W)
	MAP(27, x, X)
	MAP(28, z, Z)
	MAP(29, y, Y)
	MAP(30, 1, exclam)
	MAP(31, 2, quotedbl)
	MAP(32, 3, section)
	MAP(33, 4, dollar)
	MAP(34, 5, percent)
	MAP(35, 6, ampersand)
	EXT_MAP(36, 7, slash, braceleft, null)
	EXT_MAP(37, 8, parenleft, bracketleft, null)
	EXT_MAP(38, 9, parenright, bracketright, null)
	EXT_MAP(39, 0, equal, braceright, null)
	EXT_MAP(45, ssharp, question, backslash, null)
	MAP(46, acute, grave)
	MAP(47, udiaeresis, Udiaeresis)
	EXT_MAP(48, plus, asterisk, asciitilde, null)
	MAP(50, numbersign, apostrophe)
	MAP(51, odiaeresis, Odiaeresis)
	MAP(52, adiaeresis, Adiaeresis)
	MAP(53, asciicircum, degree)
	MAP(54, comma, semicolon)
	MAP(55, period, colon)
	MAP(56, minus, underscore)
	MAP(40, return, null)
	MAP(41, escape, null)
	MAP(42, backspace, null)
	MAP(43, tab, null)
	MAP(44, space, null)
	MAP(57, Capslock, null)
	MAP(58, F1, null)
	MAP(59, F2, null)
	MAP(60, F3, null)
	MAP(61, F4, null)
	MAP(62, F5, null)
	MAP(63, F6, null)
	MAP(64, F7, null)
	MAP(65, F8, null)
	MAP(66, F9, null)
	MAP(67, F10, null)
	MAP(68, F11, null)
	MAP(69, F12, null)
	MAP(70, Print, null)
	MAP(71, Scrollock, null)
	MAP(72, pause, null)
	MAP(73, Insert, null)
	MAP(74, Home, null)
	MAP(75, Pageup, null)
	MAP(76, delete, null)
	MAP(77, End, null)
	MAP(78, Pagedown, null)
	MAP(79, Right, null)
	MAP(80, Left, null)
	MAP(81, Down, null)
	MAP(82, Up, null)
	MAP(83, Numlock, null)
	MAP(84, KP_slash, null)
	MAP(85, KP_asterisk, null)
	MAP(86, KP_minus, null)
	MAP(87, KP_plus, null)
	MAP(88, KP_enter, null)
	MAP(89, KP_1, null)
	MAP(90, KP_2, null)
	MAP(91, KP_3, null)
	MAP(92, KP_4, null)
	MAP(93, KP_5, null)
	MAP(94, KP_6, null)
	MAP(95, KP_7, null)
	MAP(96, KP_8, null)
	MAP(97, KP_9, null)
	MAP(98, KP_0, null)
	MAP(99, KP_period, null)
	EXT_MAP(100, less, greater, bar, null)
	MAP(101, Application, null)
	MAP(102, Power, null)
	MAP(103, KP_equal, null)
	MAP(104, F13, null)
	MAP(105, F14, null)
	MAP(106, F15, null)
	MAP(116, Execute, null)
	MAP(117, Help, null)
	MAP(118, Menu, null)
	MAP(119, Select, null)
	MAP(120, Stop, null)
	MAP(121, Again, null)
	MAP(122, Undo, null)
	MAP(123, Cut, null)
	MAP(124, Copy, null)
	MAP(125, Paste, null)
	MAP(126, Find, null)
	MAP(127, Mute, null)
	MAP(128, Volumeup, null)
	MAP(129, Volumedown, null)
	MAP(224, LeftCtrl, null)
	MAP(225, LeftShift, null)
	MAP(226, LeftAlt, null)
	MAP(227, LeftMeta, null)
	MAP(228, RightCtrl, null)
	MAP(229, RightShift, null)
	MAP(230, RightAlt, null)
	MAP(231, RightMeta, null)
END_KEYMAP

