#ifndef __CONVERTSCAN_H__
#define __CONVERTSCAN_H__

#ifdef __cplusplus
   extern "C" {
#endif /* __cplusplus */

static KEYBOARD_KEY convertscan[512] = {
    0, 0, 0, 0,
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
    KEYBOARD_RETURN,
    KEYBOARD_ESCAPE,
    KEYBOARD_BACKSPACE,
    KEYBOARD_TAB,
    KEYBOARD_SPACE,
    '-',
    '=',
    '[',
    ']',
    '\\',
    '#',
    ';',
    '\'',
    '`',
    ',',
    '.',
    '/',
    KEYBOARD_CAPSLOCK,
    KEYBOARD_F1,
    KEYBOARD_F2,
    KEYBOARD_F3,
    KEYBOARD_F4,
    KEYBOARD_F5,
    KEYBOARD_F6,
    KEYBOARD_F7,
    KEYBOARD_F8,
    KEYBOARD_F9,
    KEYBOARD_F10,
    KEYBOARD_F11,
    KEYBOARD_F12,
    KEYBOARD_PRINT,
    KEYBOARD_SCROLLOCK,
    KEYBOARD_PAUSE,
    KEYBOARD_INSERT,
    KEYBOARD_HOME,
    KEYBOARD_PAGEUP,
    KEYBOARD_DELETE,
    KEYBOARD_END,
    KEYBOARD_PAGEDOWN,
    KEYBOARD_RIGHT,
    KEYBOARD_LEFT,
    KEYBOARD_DOWN,
    KEYBOARD_UP,
    KEYBOARD_NUMLOCK,
    KEYBOARD_KP_DIVIDE,
    KEYBOARD_KP_MULTIPLY,
    KEYBOARD_KP_MINUS,
    KEYBOARD_KP_PLUS,
    KEYBOARD_KP_ENTER,
    KEYBOARD_KP1,
    KEYBOARD_KP2,
    KEYBOARD_KP3,
    KEYBOARD_KP4,
    KEYBOARD_KP5,
    KEYBOARD_KP6,
    KEYBOARD_KP7,
    KEYBOARD_KP8,
    KEYBOARD_KP9,
    KEYBOARD_KP0,
    KEYBOARD_KP_PERIOD,
    0,
    KEYBOARD_APPLICATION,
    KEYBOARD_POWER,
    KEYBOARD_KP_EQUALS,
    KEYBOARD_F13,
    KEYBOARD_F14,
    KEYBOARD_F15,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    KEYBOARD_EXECUTE,
    KEYBOARD_HELP,
    KEYBOARD_MENU,
    KEYBOARD_SELECT,
    KEYBOARD_STOP,
    KEYBOARD_AGAIN,
    KEYBOARD_UNDO,
    KEYBOARD_CUT,
    KEYBOARD_COPY,
    KEYBOARD_PASTE,
    KEYBOARD_FIND,
    KEYBOARD_MUTE,
    KEYBOARD_VOLUMEUP,
    KEYBOARD_VOLUMEDOWN
};



#ifdef __cplusplus
   }
#endif /* __cplusplus */

#endif /* __CONVERTSCAN_H__ */
